name: Toolshop - UI - Tests

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: "3.12"

            - name: Install dependencies
              run: pip install -r requirements.txt

            - name: Install Chromium
              run: playwright install chromium --with-deps

            - name: Run tests
              run: pytest -v --screenshot=only-on-failure --output=test-results
              env:
                BASE_URL: ${{ secrets.BASE_URL }}
                EMAIL: ${{ secrets.EMAIL }}
                PASSWORD: ${{ secrets.PASSWORD }}
                POSTAL_CODE: ${{ secrets.POSTAL_CODE }}
                HOUSE_NUMBER: ${{ secrets.HOUSE_NUMBER }}

            - name: Upload screenshots
              if: failure()
              uses: actions/upload-artifact@v4
              with:
                name: test-results
                path: test-results/  



